import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
import { ThemeRoot } from "@repo/ui/theme/ThemeRoot";
import { cn } from "../../../packages/ui/src/lib/cn";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body
      // apply fonts globally
      className={` ${geistMono.variable}`}
      >
        <ThemeRoot
          theme="stone-dark"
          className={cn("min-h-screen bg-background font-sans antialiased", geistMono.className)}
        >
          <Providers>{children}</Providers>
        </ThemeRoot>
      </body>
    </html>
  );
}
