import type { Metadata } from "next";

import "./globals.css";
import { Providers } from "./providers";
import { AppSidebar } from "../components/app-sidebar";
import { SidebarInset } from "../components/ui/sidebar";
import { data } from "../lib/navigation";
import { Page } from "../components/page";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const NAVIGATION = data;

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html dir="ltr">
			<body>
				<Providers>
					<AppSidebar data={NAVIGATION} />
					<SidebarInset className="">
						<Page>{children}</Page>
					</SidebarInset>

					
				</Providers>
			</body>
		</html>
	);
}
