
import type { Metadata } from "next";

import "./globals.css";
import { Providers } from "./providers";
import { ThemeRoot } from "@haitch/ui";
import { cn } from "../../../packages/ui/src/lib/cn";

import { geistMono, geistSans } from "../components/fonts/fonts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html>
			<body>
				<main>
					<ThemeRoot 
						//theme="synthwave84" 
						theme="dracula"
						//theme="dark"
						//theme="light"
						//theme="stone-light"
						//theme="stone-dark"
						className={cn("min-h-screen bg-background font-sans antialiased", geistMono.variable, geistSans.variable, '')}>
						<Providers>{children}</Providers>
					</ThemeRoot>
				</main>
			</body>
		</html>
	);
}
