export const COMPS = {
	accordion: {
		description: "Component Description",
		title: "Accordion",
		componentURL: "/components/accordion",
		docURL: "/docs/accordion",
	},
	"alert-dialog": {
		description: "Component Description",
		title: "Alert Dialog",
		componentURL: "/components/alert-dialog",
		docURL: "/docs/alert-dialog",
	},
	alert: {
		description: "Component Description",
		title: "Alert",
		componentURL: "/components/alert",
		docURL: "/docs/alert",
	},
	"aspect-ratio": {
		description: "Component Description",
		title: "Aspect Ratio",
		componentURL: "/components/aspect-ratio",
		docURL: "/docs/aspect-ratio",
	},
	avatar: {
		description: "Component Description",
		title: "Avatar",
		componentURL: "/components/avatar",
		docURL: "/docs/avatar",
	},
	badge: {
		description: "Component Description",
		title: "Badge",
		componentURL: "/components/badge",
		docURL: "/docs/badge",
	},
	breadcrumb: {
		description: "Component Description",
		title: "Breadcrumb",
		componentURL: "/components/breadcrumb",
		docURL: "/docs/breadcrumb",
	},
	"button-group": {
		description: "Component Description",
		title: "Button Group",
		componentURL: "/components/button-group",
		docURL: "/docs/button-group",
	},
	button: {
		description: "Component Description",
		title: "Button",
		componentURL: "/components/button",
		docURL: "/docs/button",
	},
	calendar: {
		description: "Component Description",
		title: "Calendar",
		componentURL: "/components/calendar",
		docURL: "/docs/calendar",
	},
	card: {
		description: "Component Description",
		title: "Card",
		componentURL: "/components/card",
		docURL: "/docs/card",
	},
	carousel: {
		description: "Component Description",
		title: "Carousel",
		componentURL: "/components/carousel",
		docURL: "/docs/carousel",
	},
	chart: {
		description: "Component Description",
		title: "Chart",
		componentURL: "/components/chart",
		docURL: "/docs/chart",
	},
	checkbox: {
		description: "Component Description",
		title: "Checkbox",
		componentURL: "/components/checkbox",
		docURL: "/docs/checkbox",
	},
	"code-block": {
		description: "Component Description",
		title: "Code Block",
		componentURL: "/components/code-block",
		docURL: "/docs/code-block",
	},
	collapsible: {
		description: "Component Description",
		title: "Collapsible",
		componentURL: "/components/collapsible",
		docURL: "/docs/collapsible",
	},
	combobox: {
		description: "Component Description",
		title: "Combobox",
		componentURL: "/components/combobox",
		docURL: "/docs/combobox",
	},
	command: {
		description: "Component Description",
		title: "Command",
		componentURL: "/components/command",
		docURL: "/docs/command",
	},
	"context-menu": {
		description: "Component Description",
		title: "Context Menu",
		componentURL: "/components/context-menu",
		docURL: "/docs/context-menu",
	},
	"data-table": {
		description: "Component Description",
		title: "Data Table",
		componentURL: "/components/data-table",
		docURL: "/docs/data-table",
	},
	"date-picker": {
		description: "Component Description",
		title: "Date Picker",
		componentURL: "/components/date-picker",
		docURL: "/docs/date-picker",
	},
	dialog: {
		description: "Component Description",
		title: "Dialog",
		componentURL: "/components/dialog",
		docURL: "/docs/dialog",
	},
	drawer: {
		description: "Component Description",
		title: "Drawer",
		componentURL: "/components/drawer",
		docURL: "/docs/drawer",
	},
	"dropdown-menu": {
		description: "Component Description",
		title: "Dropdown Menu",
		componentURL: "/components/dropdown-menu",
		docURL: "/docs/dropdown-menu",
	},
	empty: {
		description: "Component Description",
		title: "Empty",
		componentURL: "/components/empty",
		docURL: "/docs/empty",
	},
	field: {
		description: "Component Description",
		title: "Field",
		componentURL: "/components/field",
		docURL: "/docs/field",
	},
	"hover-card": {
		description: "Component Description",
		title: "Hover Card",
		componentURL: "/components/hover-card",
		docURL: "/docs/hover-card",
	},
	"input-group": {
		description: "Component Description",
		title: "Input Group",
		componentURL: "/components/input-group",
		docURL: "/docs/input-group",
	},
	"input-otp": {
		description: "Component Description",
		title: "Input OTP",
		componentURL: "/components/input-otp",
		docURL: "/docs/input-otp",
	},
	input: {
		description: "Component Description",
		title: "Input",
		componentURL: "/components/input",
		docURL: "/docs/input",
	},
	item: {
		description: "Component Description",
		title: "Item",
		componentURL: "/components/item",
		docURL: "/docs/item",
	},
	kbd: {
		description: "Component Description",
		title: "Kbd",
		componentURL: "/components/kbd",
		docURL: "/docs/kbd",
	},
	label: {
		description: "Component Description",
		title: "Label",
		componentURL: "/components/label",
		docURL: "/docs/label",
	},
	"menu-bar": {
		description: "Component Description",
		title: "Menu Bar",
		componentURL: "/components/menu-bar",
		docURL: "/docs/menu-bar",
	},
	"native-select": {
		description: "Component Description",
		title: "Native Select",
		componentURL: "/components/native-select",
		docURL: "/docs/native-select",
	},
	"navigation-menu": {
		description: "Component Description",
		title: "Navigation Menu",
		componentURL: "/components/navigation-menu",
		docURL: "/docs/navigation-menu",
	},
	pagination: {
		description: "Component Description",
		title: "Pagination",
		componentURL: "/components/pagination",
		docURL: "/docs/pagination",
	},
	popover: {
		description: "Component Description",
		title: "Popover",
		componentURL: "/components/popover",
		docURL: "/docs/popover",
	},
	progress: {
		description: "Component Description",
		title: "Progress",
		componentURL: "/components/progress",
		docURL: "/docs/progress",
	},
	"radio-group": {
		description: "Component Description",
		title: "Radio Group",
		componentURL: "/components/radio-group",
		docURL: "/docs/radio-group",
	},
	resizable: {
		description: "Component Description",
		title: "Resizable",
		componentURL: "/components/resizable",
		docURL: "/docs/resizable",
	},
	"scroll-area": {
		description: "Component Description",
		title: "Scroll Area",
		componentURL: "/components/scroll-area",
		docURL: "/docs/scroll-area",
	},
	select: {
		description: "Component Description",
		title: "Select",
		componentURL: "/components/select",
		docURL: "/docs/select",
	},
	separator: {
		description: "Component Description",
		title: "Separator",
		componentURL: "/components/separator",
		docURL: "/docs/separator",
	},
	sheet: {
		description: "Component Description",
		title: "Sheet",
		componentURL: "/components/sheet",
		docURL: "/docs/sheet",
	},
	sidebar: {
		description: "Component Description",
		title: "Sidebar",
		componentURL: "/components/sidebar",
		docURL: "/docs/sidebar",
	},
	skeleton: {
		description: "Component Description",
		title: "Skeleton",
		componentURL: "/components/skeleton",
		docURL: "/docs/skeleton",
	},
	slider: {
		description: "Component Description",
		title: "Slider",
		componentURL: "/components/slider",
		docURL: "/docs/slider",
	},
	toast: {
		description: "Component Description",
		title: "Toast",
		componentURL: "/components/toast",
		docURL: "/docs/toast",
	},
	spinner: {
		description: "Component Description",
		title: "Spinner",
		componentURL: "/components/spinner",
		docURL: "/docs/spinner",
	},
	switch: {
		description: "Component Description",
		title: "Switch",
		componentURL: "/components/switch",
		docURL: "/docs/switch",
	},
	table: {
		description: "Component Description",
		title: "Table",
		componentURL: "/components/table",
		docURL: "/docs/table",
	},
	tabs: {
		description: "Component Description",
		title: "Tabs",
		componentURL: "/components/tabs",
		docURL: "/docs/tabs",
	},
	"text-area": {
		description: "Component Description",
		title: "Text Area",
		componentURL: "/components/text-area",
		docURL: "/docs/text-area",
	},
	"toggle-group": {
		description: "Component Description",
		title: "Toggle Group",
		componentURL: "/components/toggle-group",
		docURL: "/docs/toggle-group",
	},
	toggle: {
		description: "Component Description",
		title: "Toggle",
		componentURL: "/components/toggle",
		docURL: "/docs/toggle",
	},
	tooltip: {
		description: "Component Description",
		title: "Tooltip",
		componentURL: "/components/tooltip",
		docURL: "/docs/tooltip",
	},
	typography: {
		description: "Component Description",
		title: "Typography",
		componentURL: "/components/typography",
		docURL: "/docs/typography",
	},
	tree: {
		description: "Component Description",
		title: "Tree",
		componentURL: "/components/tree",
		docURL: "/docs/tree",
	},
};

const registry = COMPS;

export { registry };
